const routes = {
  home: "/main-home",
  profile: "/Setting",
  login: "/login",
  register: "/register",
  resetPassword: "/reset-password",
  changePassword: "/change-password",
  forgotPassword: "/forgot-password",
  otp: "/otp",
  notFound: "*",
  coding: "/coding",
  indexHome: "/",
  admin: {
    dashboard: "/admin",
    lecture: "admin/lecture",
    problemPageAdmin: "/problemsAdmin",
    coursePageAdmin: "/coursesAdmin",
  },
  problemPage: "/problems",
  coursePage: "/courses",
  courseDetail: "/courses/detail/:id",
  lecture: "/courses/detail/lecture/:id",
  newCourse: "/new-courses/:id",
  contactPage: "/contact",
  solveProblem: "/problems/solve/:id",
  communityPage: "/community",
  detailPost: "/community/post/detail/:id",
  playgroundPage: "/playground",
  myPosts: "/community/profile/:userId",
};

export default routes;
